Integrated Mayhem
mayhemheroes/RustPython pull request #1
Opened 2023-04-25 20:20 UTC by 4812571

Integrated Mayhem, an automated fuzz testing solution

2023-04-27 20:37 UTC, xansec requested changes
Please make the requested changes.

2023-04-27 20:37 UTC, xansec commented on .github/workflows/mayhem.yml
> +name: Mayhem
Can you please use the latest workflow example here: https://github.com/mayhemheroes/mayhem-cmake-example/blob/solution/.github/workflows/mayhem.yml

2023-05-02 01:22 UTC, 4812571 commented
Changes made @xansec!

2023-05-02 01:22 UTC, 4812571 commented
Also, do you know how I could squash these commits? It failed for me because there is a merge among them.

2023-05-02 07:43 UTC, 4812571 commented
I also had some missing binaries in my cargo manifest. I have added those as well

2023-05-07 06:32 UTC, xansec approved these changes
I added the merge commits. LGTM!

2023-05-07 06:32 UTC, merged